import { Scenario, soundTypes } from '../../types/Scenario';

const forest: Scenario = {
  id: 1,
  name: 'Forest',
  slug: 'forest',
  description: 'Forest with small stream and birdsong',
  sounds: {
    forestBirds: {
      id: 0,
      slug: 'forestBirds',
      name: 'Forest birds',
      type: soundTypes.background,
      paths: ['forest-birds.mp3'],
      volume: 0.9,
      frequency: 0,
      area: [
        [0, 0, 0],
        [0, 0, 0],
      ],
      mute: false,
    },
    rain2: {
      id: 1,
      slug: 'smallStream',
      name: 'Small Stream',
      type: soundTypes.background,
      paths: ['small-stream.mp3'],
      volume: 0.4,
      frequency: 0,
      area: [
        [0.5, 0, 0],
        [0.5, 0, 0],
      ],
      mute: false,
    },
    blackbird: {
      id: 2,
      slug: 'blackbird',
      name: 'Blackbird',
      type: soundTypes.random,
      paths: [
        'blackbird/blackbird-1.mp3',
        'blackbird/blackbird-2.mp3',
        'blackbird/blackbird-3.mp3',
        'blackbird/blackbird-4.mp3',
        'blackbird/blackbird-5.mp3',
        'blackbird/blackbird-6.mp3',
        'blackbird/blackbird-7.mp3',
        'blackbird/blackbird-8.mp3',
        'blackbird/blackbird-9.mp3',
        'blackbird/blackbird-10.mp3',
        'blackbird/blackbird-11.mp3',
        'blackbird/blackbird-12.mp3',
        'blackbird/blackbird-13.mp3',
        'blackbird/blackbird-14.mp3',
        'blackbird/blackbird-15.mp3',
      ],
      volume: 0.5,
      frequency: 0.3,
      area: [
        [-2, 1, -2],
        [2, 2, 2],
      ],
      mute: false,
    },
    chaffinch: {
      id: 3,
      slug: 'chaffinch',
      name: 'Chaffinch',
      type: soundTypes.random,
      paths: [
        'chaffinch/chaffinch-1.mp3',
        'chaffinch/chaffinch-2.mp3',
        'chaffinch/chaffinch-3.mp3',
        'chaffinch/chaffinch-4.mp3',
        'chaffinch/chaffinch-5.mp3',
        'chaffinch/chaffinch-6.mp3',
      ],
      volume: 0.5,
      frequency: 0.3,
      area: [
        [-2, 1, -2],
        [2, 2, 2],
      ],
      mute: false,
    },
    cuckcoo: {
      id: 4,
      slug: 'cuckoo',
      name: 'Cuckoo',
      type: soundTypes.random,
      paths: [
        'cuckoo/cuckoo-1.mp3',
        'cuckoo/cuckoo-2.mp3',
        'cuckoo/cuckoo-3.mp3',
        'cuckoo/cuckoo-4.mp3',
        'cuckoo/cuckoo-5.mp3',
        'cuckoo/cuckoo-6.mp3',
        'cuckoo/cuckoo-7.mp3',
      ],
      volume: 0.5,
      frequency: 0.25,
      area: [
        [-2, 1, -2],
        [2, 2, 2],
      ],
      mute: false,
    },
    frog: {
      id: 5,
      slug: 'frog',
      name: 'Frog',
      type: soundTypes.random,
      paths: [
        'frog/frog-1.mp3',
        'frog/frog-2.mp3',
        'frog/frog-3.mp3',
        'frog/frog-4.mp3',
        'frog/frog-5.mp3',
        'frog/frog-6.mp3',
        // 'frog/frog-copes.mp3',
      ],
      volume: 0.25,
      frequency: 0.25,
      area: [
        [-2, 1, -2],
        [2, 2, 2],
      ],
      mute: false,
    },
    songThrush: {
      id: 6,
      slug: 'songThrush',
      name: 'Song Thrush',
      type: soundTypes.random,
      paths: [
        'song-thrush/song-thrush-1.mp3',
        'song-thrush/song-thrush-2.mp3',
        'song-thrush/song-thrush-3.mp3',
        'song-thrush/song-thrush-4.mp3',
        'song-thrush/song-thrush-5.mp3',
        'song-thrush/thrush-1.mp3',
        'song-thrush/thrush-2.mp3',
      ],
      volume: 0.5,
      frequency: 0.25,
      area: [
        [-2, 1, -2],
        [2, 2, 2],
      ],
      mute: false,
    },
    treeFalling: {
      id: 7,
      slug: 'treeFalling',
      name: 'Tree Falling',
      type: soundTypes.random,
      paths: ['tree-falling/tree-falling.mp3'],
      volume: 0.5,
      frequency: 0.05,
      area: [
        [-2, 1, -2],
        [2, 2, 2],
      ],
      mute: false,
    },
    woodPidgeon: {
      id: 8,
      slug: 'woodPidgeon',
      name: 'Wood Pidgeon',
      type: soundTypes.random,
      paths: [
        'wood-pidgeon/wood-pidgeon-1.mp3',
        'wood-pidgeon/wood-pidgeon-2.mp3',
        'wood-pidgeon/wood-pidgeon-3.mp3',
        'wood-pidgeon/wood-pidgeon-4.mp3',
        'wood-pidgeon/wood-pidgeon-5.mp3',
      ],
      volume: 0.5,
      frequency: 0.25,
      area: [
        [-2, 1, -2],
        [2, 2, 2],
      ],
      mute: false,
    },
    woodpecker: {
      id: 9,
      slug: 'woodpecker',
      name: 'Woodpecker',
      type: soundTypes.random,
      paths: [
        'woodpecker/woodpecker-1.mp3',
        'woodpecker/woodpecker-2.mp3',
        'woodpecker/woodpecker-3.mp3',
        'woodpecker/woodpecker-4.mp3',
      ],
      volume: 0.5,
      frequency: 0.25,
      area: [
        [-2, 1, -2],
        [2, 2, 2],
      ],
      mute: false,
    },
  },
};

export default forest;
